### PR TITLE
Change @Component to Guice @Inject

### PR DESCRIPTION
**Pull request by elharo**
Need to check where this code is used. There are many subclasses spread across different plugins. Not sure how to navigate this.

### CODE REVIEW

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]
It is used in every site reports plugin ... I wouldn't do such change

**Comment by elharo** [comment]
At some point we do want to get rid of the old plexus injection completely. It's worth thinking about how we're going to finish that job. If only we had a monorepo, and if wishes were horses...

**Comment by michael-o** [comment]
How does this behave with concrete impls?

**Comment by elharo** [comment]
They're going to need to change so the injection happens in the subclass and the values are passed up the chain in a call to super. I've already done or am in the process of doing this in other plugins. The difference here is we don't have all the dependents in the same repo. :-(

**Comment by elharo** [comment]
We can try field injection as an intermediate step but we should get away from this eventually. It makes classes mutable and bypasses the usual object initialization, which is unnecessarily risky. It's also harder to write tests for.

**Comment by michael-o** [comment]
Moving to da draft because I cannot estimate the impact...

**Review by slawekjaranowski — APPROVED** [review]
Now by fields injection it is safe

**Pull request merged**
