### PR TITLE
[MSHARED-1392] Upgrade to Parent 42 and Maven 3.6.3

### PR DESCRIPTION
**Pull request by michael-o**
@cstamas Can you tell me whether the Maven dependencies should move to `provided` scope?

### CODE REVIEW

**Comment by cstamas** [comment]
Anything that executes "like a maven plugin" should have them provided. Now, in case of site/reports am aware you have some intermediate libs that are not plugins, but can execute only in context of plugin/report. 

It does not have to, as "root" dependency will be plugin (or report that is like a plugin) and it will force maven deps into provided anyway (as these intermediate stuff will always be deeper in dep tree).

**Comment by michael-o** [comment]
> Anything that executes "like a maven plugin" should have them provided. Now, in case of site/reports am aware you have some intermediate libs that are not plugins, but can execute only in context of plugin/report.
> 
> It does not have to, as "root" dependency will be plugin (or report that is like a plugin) and it will force maven deps into provided anyway (as these intermediate stuff will always be deeper in dep tree).

Yes, reporting impl always executes as a Maven Plugin from command line, so provided seems to be right here.

**Comment by michael-o** [comment]
@cstamas Changed, please have a look.

**Review by slawekjaranowski — APPROVED** [review]

**Comment by cstamas** [comment]
If you check out this: https://github.com/apache/maven/blob/maven-3.9.x/maven-core/src/main/resources/META-INF/maven/extension.xml
you will see that same stands for plexus...

There is ONE tricky dep: resolver-util
IF you don't use it, nothing. IF YOU DO use it, it has to be _compile_ to make compatible with Maven 3.8 and 3.9 (where change happened, as resolver-util became provided as well, it was not in previous versions).

**Review by cstamas — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #173

**Pull request closed without merging**
